---
title: "zglab3"
author: "Zane"
date: "August 31, 2018"
output: html_document
fig_caption: yes
keep_md: yes
number_sections: yes
toc: yes
toc_float: yes
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(s20x)
library(magrittr)
library(gridExtra)
library(kableExtra)
library(grid)
library(knitr)
library(purrr)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)

```

##Task 1
```{r t1}
SPRUCE <- read_csv("DATAxls/SPRUCE.csv")
getwd()
```
##Task 2
```{r t2}
head(SPRUCE)
```

##task 3
```{r t3}
sprucePlot <- ggplot(SPRUCE, aes(BHDiameter, Height))
(scatterPlot <- sprucePlot+
  geom_point(color = "blue", fill = "blue", shape = 21, size = 2.1)+
  coord_cartesian(xlim = c(0, 1.1 * max(SPRUCE$BHDiameter), ylim = c(0, 1.1 * max(SPRUCE$Height)))))
par(mfrow = c(1, 3))
for(i in c(0.5, 0.6, 0.7))
  trendscatter(Height~BHDiameter, f = i, data = SPRUCE, main = paste("f: ", as.character(i)))
(spruce.lm <- lm(Height~BHDiameter, data = SPRUCE))
(lmPlot <- scatterPlot + geom_smooth(method = lm, se = FALSE))
```
This plot doesn't seem like  a very good fit

##Task 4
```{r t4}

predictions <- as.numeric(predict.lm(spruce.lm))
BHDcPred <- c(predictions, SPRUCE$BHDiameter)

grid.arrange(
  lmPlot,
  lmPlot + geom_segment(aes(xend = BHDiameter, yend = predictions)),
  lmPlot + geom_segment(aes(xend = BHDiameter, yend = mean(BHDcPred)))+
    geom_hline(aes(yintercept = mean(BHDcPred))),
  scatterPlot + geom_hline(aes(yintercept = mean(BHDcPred)))+
    geom_segment(aes(xend = BHDiameter, yend = mean(BHDcPred)))
)

data.frame(
    "TSS"=(SPRUCE$Height-mean(SPRUCE$Height))^2,
    "MSS"=(predictions-mean(SPRUCE$Height))^2,
    "RSS"=(SPRUCE$Height-predictions)^2
)%>%
  summarise_all(funs(sum))%>%
  mutate(RSS,MSS,RSS+MSS)%>%
  mutate(TSS,MSS,MSS/TSS)%>%
  kable()%>%
  kable_styling("striped","condensed")%>%
  column_spec(1, width="5cm")
```
##Task 5
```{r t5}
summary(spruce.lm)
predict(spruce.lm,data.frame(BHDiameter=c(15,18,20)))%>%
  data.frame(c("15","18","20"))%>%
  kable()%>%
  kable_styling("striped","condensed")%>%
  
  column_spec(1, width="5cm")
```

##Task 6
```{r t6}
sprucePlot+
  geom_point(aes(color=BHDiameter))+
  geom_smooth(method=lm,aes(color=BHDiameter))+
  geom_line(aes(color=BHDiameter))+
  labs(title="Height vs BHDiameter")

```